version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install -g mocha jest

  pre_build:
    commands:
      - echo "Configuring AWS credentials for EKS..."
      - aws eks update-kubeconfig --region ap-south-1 --name aws_cicd_cluster

      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 390844759906.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t cicd_aws .
      - docker tag cicd_aws:latest 390844759906.dkr.ecr.ap-south-1.amazonaws.com/cicd_aws:latest

  post_build:
    commands:
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push 390844759906.dkr.ecr.ap-south-1.amazonaws.com/cicd_aws:latest

      - echo "Updating EKS authentication with mapRoles.yaml..."
      - kubectl apply -f mapRoles.yaml  # Add this line

      - echo "Deploying to EKS..."
      - kubectl apply -f deployment.yaml

      - echo "Waiting for deployment to complete..."
      - kubectl rollout status deployment nginx-api-pod || kubectl get pods -o wide

artifacts:
  files:
    - '**/*'
