apiVersion: v1
kind: Pod
metadata:
  name: nginx-api-pod
  labels:
    app: nginx-api  # A more general label, makes it easier for scaling purposes
    type: web-app   # Optional label to describe the app's purpose
spec:
  containers:
    - name: nginx1
      image: 390844759906.dkr.ecr.ap-south-1.amazonaws.com/cicd_aws:latest  # Ensure the ECR image path is correct
      imagePullPolicy: Always  # Always pull the latest version
      ports:
        - containerPort: 8000  # Ensure this matches your app's exposed port
      resources:
        requests:
          memory: "256Mi"  # Example resource request
          cpu: "250m"      # Example CPU request
        limits:
          memory: "512Mi"  # Example resource limit
          cpu: "500m"      # Example CPU limit
