version: '3'
services:
  nginx1:
    build: .
    container_name: nginx1
    ports:
      - "8000:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my_app_network

  nginx2:
    build: .
    container_name: nginx2
    ports:
      - "8001:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my_app_network

  # Add Node.js API container
  my-api:
    build:
      context: ./path-to-api  # Path to your Node.js API code
      dockerfile: Dockerfile.node  # Ensure you have a separate Dockerfile for Node.js
    container_name: my-api
    ports:
      - "3000:3000"  # Expose the API on port 3000
    networks:
      - my_app_network

  # Add MySQL container
  mysql-server:
    image: mysql:latest
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    networks:
      - my_app_network

networks:
  my_app_network:
    driver: bridge
