
services:
  nginx1: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx1
    ports: 
      - "8000:80"
    volumes: 
      - ./Signup.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my_app_network

  nginx2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx2
    ports:
      - "8001:80"
    volumes:
      - ./Signup.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my_app_network

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_container
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: Admin@123
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    networks:
      - my_app_network
    # healthcheck:
    #   test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Admin@123", "-Q", "SELECT 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3

  my-api:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: api-container
    ports:
      - "3000:3000"
    networks:
      - my_app_network
    environment:
      - DB_HOST=sql_server_container
      - DB_USER=sa
      - DB_PASSWORD=Admin@123
      - DB_NAME=Testdb
      - DB_PORT=1433
    volumes:
      - .:/app
    
networks:
  my_app_network:
    driver: bridge
