services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: Testdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password
    ports:
      - "3306:3306"
    networks:
      - my_app_network

  my-api:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: api-container
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root_password
      DB_NAME: Testdb
    ports:
      - "3000:3000"
    networks:
      - my_app_network
    depends_on:
      - mysql

networks:
  my_app_network:
    driver: bridge
