version: '3'
services:
  nginx1:
    build: .
    container_name: nginx1
    ports:
      - "8000:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  nginx2:
    build: .
    container_name: nginx2
    ports:
      - "8001:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
