services:
  nginx1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx1
    ports:
      - "8000:80"
    volumes:
      - ./Signup.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my_app_network

  # nginx2:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: nginx2
  #   ports:
  #     - "8001:80"
  #   volumes:
  #     - ./Signup.html:/usr/share/nginx/html/index.html
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   networks:
  #     - my_app_network

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_container
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: Admin@123
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    networks:
      - my_app_network

  my-api:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: api-container
    ports:
      - "8001:80"
    networks:
      - my_app_network
    environment:
      - DB_HOST=sql_server_container
      - DB_USER=sa
      - DB_PASSWORD=Admin@123
      - DB_NAME=Testdb
      - DB_PORT=1433
    volumes:
      - .:/app
    depends_on:
      - sql-server


networks:
  my_app_network:
    driver: bridge
