# Use the official Node.js 18 image as the base
FROM node:18

# Set the working directory inside the container
WORKDIR /app

# Copy the application files (excluding node_modules via .dockerignore)
COPY . .

# Remove existing node_modules and package-lock.json if present
# RUN rm -rf node_modules package-lock.json

# Reinstall dependencies
RUN npm install


# Expose the port that the API will run on
EXPOSE 3000

# Start the API server
CMD ["node", "server.js"]
