apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::390844759906:role/codebuild-cicd_aws-service-role
      username: build
      groups:
        - system:masters
