apiVersion: v1
kind: Pod
metadata:
  name: nginx-api-pod
  labels:
    run: nginx-api-pod  # You can label it as nginx-api or any name that represents both containers
    type: web-app   # An additional label to describe the purpose (optional)
spec:
  containers:
    - name: nginx1
      image: israni141/devops:nginx1-latest
      imagePullPolicy: Always
      ports:
        - containerPort: 8000

